### ISSUE TITLE
Server crashes from 90+ second hang

### ISSUE THREAD

**Issue by ghost** [CyclopsMC/IntegratedCrafting#34]
#### Issue type:

- :bug: Bug

____

#### Short description:

Our server is suddenly locked up. It has been operating fine at 20+ fps for the entirety of it's existence, now it's just completely bricked whenever I start it up. I can't even do so much as get a command through the console before it times out after 90+ seconds.

```
java.lang.Error: ServerHangWatchdog detected that a single server tick took 96.16 seconds (should be max 0.05)
	at org.cyclops.commoncapabilities.ingredient.IngredientSerializerItemStack.deserializeInstance(IngredientSerializerItemStack.java:31)
	at org.cyclops.commoncapabilities.ingredient.IngredientSerializerItemStack.deserializeInstance(IngredientSerializerItemStack.java:14)
	at org.cyclops.commoncapabilities.api.ingredient.IMixedIngredients.deserialize(IMixedIngredients.java:139)
	at org.cyclops.integratedcrafting.api.crafting.CraftingJob.deserialize(CraftingJob.java:188)
	at org.cyclops.integratedcrafting.core.CraftingJobHandler.readFromNBT(CraftingJobHandler.java:168)
	at org.cyclops.integratedcrafting.part.PartTypeInterfaceCrafting$State.readFromNBT(PartTypeInterfaceCrafting.java:395)
	at org.cyclops.integrateddynamics.api.part.PartTypeAdapter.fromNBT(PartTypeAdapter.java:56)
	at org.cyclops.integrateddynamics.core.helper.PartHelpers.readPartFromNBT(PartHelpers.java:165)
	at org.cyclops.integrateddynamics.core.helper.PartHelpers.readPartsFromNBT(PartHelpers.java:188)
	at org.cyclops.integrateddynamics.capability.partcontainer.PartContainerDefault.deserializeNBT(PartContainerDefault.java:241)
	at org.cyclops.integrateddynamics.core.tileentity.TileMultipartTicking.func_145839_a(TileMultipartTicking.java:130)
	at net.minecraft.tileentity.TileEntity.func_190200_a(TileEntity.java:120)
```

#### Steps to reproduce the problem:

 I'm unsure, unfortunately it is on my server and I haven't been able to track down any users may have triggered this. I hope that you are able to glean something from the crash log.

#### Expected behaviour:

Self explanatory, I hope
____

#### Versions:

- This mod: 1.0.7
- Minecraft: 1.12.2
- Forge: 14.23.5.2838

#### Log file:

[Full log](https://pastebin.com/UYtVS9GU)

---
In the mean time I suppose I will just remove the mod, restart the server, then add the mod back in and restart again, and just accept that people will lose their Integrated Crafting blocks.

Edit: Indeed, this is what I did and it fixed the issue, although obviously it's not ideal because everyone lost all their blocks from the mod

**Comment by rubensworks** [comment]
That's not good. Looks similar to #32.

Perhaps you can repair your server by starting ID in safe-mode (see ID config file), but not sure that will work here.

**Comment by rubensworks** [comment]
For reference, this was caused by a large amount of pending crafting jobs.
A (configurable) limitation for this will be available in the new version.
